version: "3.3"

services:
  api:
    container_name: api
    restart: always
    build:
      context: .
    image: selub/postup:latest
    env_file: docker-compose.env
    environment:
      SERVICES: api # Moleculer Runner will start only the 'api' service in this container
      PORT: 3000 # Port of API gateway
    depends_on:
      - mqtt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"

  posts:
    restart: always
    container_name: posts
    build:
      context: .
    image: selub/postup:latest
    env_file: docker-compose.env
    environment:
      SERVICES: posts # Moleculer Runner will start only the 'posts' service in this container
    depends_on:
      - api
      - mqtt

  storage:
    restart: always
    container_name: storage
    build:
      context: .
    image: selub/postup:latest
    env_file: docker-compose.env
    environment:
      SERVICES: storage # Moleculer Runner will start only the 'storage' service in this container
    depends_on:
      - api
      - mqtt

  bots:
    restart: always
    container_name: bots
    build:
      context: .
    image: selub/postup:latest
    env_file: docker-compose.env
    environment:
      SERVICES: bots # Moleculer Runner will start only the 'storage' service in this container
    depends_on:
      - mqtt
      - posts

  channels:
    restart: always
    container_name: channels
    build:
      context: .
    image: selub/postup:latest
    env_file: docker-compose.env
    environment:
      SERVICES: channels # Moleculer Runner will start only the 'storage' service in this container
    depends_on:
      - mqtt
      - posts

  publishers:
    restart: always
    container_name: publishers
    build:
      context: .
    image: selub/postup:latest
    env_file: docker-compose.env
    environment:
      SERVICES: publishers # Moleculer Runner will start only the 'storage' service in this container
    depends_on:
      - mqtt
      - posts

  traefik:
    container_name: traefik
    image: traefik:v2.1
    restart: always
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mqtt:
    image: eclipse-mosquitto:1.6.15
    restart: always
    hostname: mqtt
    container_name: mqtt
    ports:
      - "1883:1883"

  # nats:
  #   image: nats
  #   restart: always
  #   hostname: nats
  #   container_name: nats
  #   ports:
  #     - "4222:4222"
  #   networks:
  #     - internal
  #     - default
  db:
    image: postgres:latest
    networks:
      - internal
    env_file: docker-compose.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
networks:
  internal:
# volumes:
#   db_data:
